### PR TITLE
Don't call destroyResource twice

### PR DESCRIPTION
**Pull request by womeier**
forgot to delete these lines in the test file

### CODE REVIEW

**Comment by womeier** [comment]
this does not fix the segfault unfortunately

**Comment by womeier** [comment]
@yilinke  this should have been in my PR yesterday

**Comment by womeier** [comment]
Testlog preprocess test:

before:

colorization/src/tests.py Acl init success
Open device  0  success.
called destroy resource of colorize_process
finished destroy resource of colorize_process
called destroy resource of colorize_process
Release image abnormaly, data is None
called destructor of model process.
destructor of model process finished.
tear down called

after:

colorization/src/tests.py Acl init success
Open device  0  success.
called destroy resource of colorize_process
finished destroy resource of colorize_process
called destructor of model process.
destructor of model process finished.
tear down called

**Comment by yilinke** [comment]
OK, i see this difference of destroy(destructor).

**Review by yilinke — APPROVED** [review]

**Pull request merged**
